name: Tests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Syntax
        run: |
          make syntax
